starkware-libs/starkware-starknet-utils

src/constants.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/16)

chore(cairo): change TWO_POW_32 to i64

---

src/test_utils.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/21)

chore(cairo): add set_account_as_app_governor

---

Scarb.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/22)

fix(cairo): Scarb.lock

---

.github/workflows/on-pull-request.yaml
Scarb.lock
Scarb.toml
src/bit_mask.cairo
src/bit_set.cairo
src/components/deposit/deposit.cairo
src/components/deposit/interface.cairo
src/components/nonce/nonce.cairo
src/components/replaceability/eic_test_contract.cairo
src/components/replaceability/replaceability.cairo
src/components/replaceability/test.cairo
src/components/replaceability/test_utils.cairo
src/components/request_approvals/request_approvals.cairo
src/components/roles/test.cairo
src/components/roles/test_utils.cairo
src/iterable_map.cairo
src/span_utils.cairo
src/test_utils.cairo
src/tests/test_iterable_map.cairo
src/trace/trace.cairo
src/utils.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/23)

chore(cairo): update to scarb 2.11.0

---

.github/workflows/on-pull-request.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/25)

ci(utils): add cov

---

src/constants.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/27)

feat(cairo): use pow

---

src/components/deposit/deposit.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/28)

feat(cairo): make deposit hash fn pub

---

src/iterable_map.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/31)

fix(cairo): iterable map storage node

---

src/math/fraction.cairo
src/utils.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/34)

chore(fraction): make non generic

---

src/components/replaceability/test.cairo
src/components/replaceability/test_utils.cairo
src/components/roles/test.cairo
src/components/roles/test_utils.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/37)

feat(cairo): remove ContractAddress fns

---

.github/workflows/autoupdate.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/38)

chore(ci): add auto update workflow

---

.github/workflows/on-pull-request.yaml
Scarb.toml
packages/testing/Scarb.lock
packages/testing/Scarb.toml
packages/testing/src/event_test_utils.cairo
src/components/replaceability/test_utils.cairo
src/components/roles/event_test_utils.cairo
src/tests/test_message_hash.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/35)

chore(cairo): bump version

---

src/interfaces.cairo
src/interfaces/mintable_token.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/41)

feat(cairo): mintable token interface

---

packages/testing/src/constants.cairo
packages/testing/src/lib.cairo
src/components/roles/test.cairo
src/components/roles/test_utils.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/42)

feat(testing): move consts

---

src/trace/mock.cairo
src/trace/test.cairo
src/trace/trace.cairo

1. rename pos to len
2. remove binary search
3. move _insert to fn insert (different commit)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/40)

fix(trace): rename pos to len

---

Scarb.lock
Scarb.toml
packages/testing/README.md
packages/testing/Scarb.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/43)

chore(cairo): organize packages

---

.github/workflows/publish-testing.yml
.github/workflows/publish.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/44)

ci: publish to scarb.xyz

---

.github/workflows/publish-testing.yml
.github/workflows/publish.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/45)

fix: publish to scarb.xyz

---

.github/workflows/publish.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/47)

fix(ci): publish to scarb.xyz

---

.github/workflows/publish-testing.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/48)

fix(ci): publsh to scarb.xyz

---

Scarb.lock
Scarb.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/54)

Release v0.1.1

---

packages/testing/Scarb.toml
packages/testing/src/event_test_utils.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/61)

ci: fix for testing release

---

packages/testing/src/test_utils.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/64)

chore(staking): change assert error message in assert_expected_error

---

packages/utils/src/interfaces/mintable_token.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/68)

fix(token): return bool

---

packages/utils/src/math/utils.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/69)

feat(math): u256_reverse_endian u256_from_u32_array

---

packages/utils/src/math/utils.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/71)

feat(math): add wide mul and floor div

---

packages/utils/src/message_hash.cairo
packages/utils/src/tests/test_message_hash.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/72)

fix(snip12): revision to be integer

---

Scarb.lock
Scarb.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/70)

chore(staking): change snforge and openzeppelin_testing version

---

packages/utils/src/lib.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/85)

fix(utils): add the erc20 mod

---

packages/utils/src/erc20/erc20_mocks.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/88)

feat(erc20): add erc20 mock contract with decimals

---

packages/utils/src/erc20/erc20_mocks.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/89)

fix(erc20): fix erc20 mock contract metadata

---

Scarb.lock
Scarb.toml
packages/testing/Scarb.toml
packages/utils/Scarb.toml
packages/utils/src/erc20/erc20_mocks.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/90)

chore(cairo): update oz versions

---

.gitignore
python/pyproject.toml
python/test_utils/__init__.py
python/test_utils/conftest.py
python/test_utils/starknet_test_utils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/93)

feat: python utils

---

python/test_utils/starknet_test_utils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/95)

fix: path arg

---

python/test_utils/starknet_test_utils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/97)

chore: remove shell = true

---

packages/utils/src/trace/trace.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/100)

chore(trace): as_non_mut

---

packages/utils/src/trace/trace.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/104)

chore(trace): nth_back

---

packages/utils/src/trace/mock.cairo
packages/utils/src/trace/test.cairo
packages/utils/src/trace/trace.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/99)

feat(trace): antepenultimate function

---

packages/utils/src/storage/iterable_map.cairo
packages/utils/src/storage/tests/test_iterable_map.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/103)

feat(iter-map): clear function

---

packages/utils/src/trace/mock.cairo
packages/utils/src/trace/test.cairo
packages/utils/src/trace/trace.cairo

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/starkware-starknet-utils/109)

chore(trace): rename latest, penultimate, antepenultimate
